version: "3"
services:  
  traefik:
    build:
      context: ./build
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Brussels
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./traefik:/etc/traefik"
    networks:
      - traefik
      - wireguard-isolated_isolated-vpn

  whoami:
    image: "traefik/whoami"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    name: traefik
  wireguard-isolated_isolated-vpn:
    external: true