http:
  routers:
    lannootree_router:
      entryPoints:
        - websecure
      rule: Host(`lannootree.devbitapp.be`)
      service: lannootree_service
      tls:
        certResolver: production

    traefik_lannootree_router:
      entryPoints:
        - websecure
      rule: Host(`traefik.lannootree.devbitapp.be`)
      service: lannootree_service
      tls:
        certResolver: production

    auth_lannootree_router:
      entryPoints:
        - websecure
      rule: Host(`auth.lannootree.devbitapp.be`)
      service: lannootree_service
      tls:
        certResolver: production

    # phpmyadmin_lannootree_router:
    #   entryPoints:
    #     - websecure
    #   rule: Host(`phpmyadmin.lannootree.devbitapp.be`)
    #   service: phpmyadmin_service
    #   tls:
    #     certResolver: production

    whoami_router:
      entryPoints:
        - websecure
      rule: Host(`whoami.vps.arnos.be`)
      service: whoami_service
      tls:
        certResolver: production


  services:
    lannootree_service:
      loadBalancer:
        servers:
          - url: http://10.20.31.2:80
    # lannootree_service:
    #   loadBalancer:
    #     servers:
    #       - url: http://lannootree-traefik:80

    phpmyadmin_service:
      loadBalancer:
        servers:
          - url: http://10.20.31.2:8080

    whoami_service:
      loadBalancer:
        servers:
          - url: http://whoami:80

